### ISSUE TITLE
Error while compiling ESP-

### ISSUE THREAD

**Issue by AdaBill** [lukecyca/esp-sous-vide#2]
Luke,

I made a little progress since your last help  .. But i didn't get very far.

While compiling , I ran into the following error.

esp-sous-vide:118: error: 'POSITIVE' was not declared in this scope

 LiquidCrystal_I2C lcd(0x3F, 2, 1, 0, 4, 5, 6, 7, 3, POSITIVE);

I checked and it looks like I have all the correct libraries
although I received the following compiler warning: WARNING: library LiquidCrystal_I2C claims to run on [avr] architecture(s) and may be incompatible with your current board which runs on [esp8266] architecture(s).

Where did you get your LiquicCrystal_I2C library to make sure I'm using the same one?

**Comment by lukecyca** [comment]
I'm currently using LiquidCrystal_V1.2.1.zip from https://bitbucket.org/fmalpartida/new-liquidcrystal/downloads/

I see now that there are newer versions. I should probably upgrade.

This website has lots of information about using the i2c backpacks: https://arduino-info.wikispaces.com/LCD-Blue-I2C

**Comment by AdaBill** [comment]
Luke, I downloaded that library and it still did not resolve the issue.  I searched all its members and none contained a reference to 'POSITIVE'.

How do I get it to compile if there is no reference to this variable.

**Comment by AdaBill** [comment]
Luke,

SORRY.. I downloaded the wrong library, and when I went back and did it again, with the library you mentioned above, It DOES COMPILE..  Sorry for the fat fingers.

Now I'll try to get it set up and run.  might take a couple days.

thanks for your help.
